version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: louna
    restart: unless-stopped
    env_file: .env
    ports: 
     - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
     - redis
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis-data:/root/redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"


