services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: louna
    restart: unless-stopped
    env_file: .env
    ports: 
     - "${HTTP_PORT}:${HTTP_PORT}"
    links:
      - redis_louna
      - postgres_louna
    depends_on:
      redis_louna:
        condition: service_healthy
      postgres_louna:
        condition: service_started
  redis_louna:
    container_name: redis_louna
    image: redis:latest
    restart: always
    env_file: .env
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
    volumes:
      - /var/lib/redis-data:/root/redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
  postgres_louna: 
    container_name: postgres_louna
    image: postgres:15
    env_file: .env
    shm_size: 10g
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
